#!/usr/bin/env bash

set -e

echo "---> Add Config"

/usr/local/bin/gen-config-${DISTRO_DB_DIALECT} > /distro/.dredd/config.json

echo "---> Waiting for distro"
while ! nc -z distro_ci 3000; do
  sleep 1
done

echo "---> Run Dredd"
# We do this because otherwise it can fail out
sleep 5
dredd $@
