#!/usr/bin/env bash

cat <<EOF
{
	"postgres": {
		"host": "postgres:5432",
		"user": "distro",
		"pass": "distro",
		"name": "distro",
    "options": {
      "sslmode": "disable"
    }
	},
	"dialect": "postgres",
	"access_key_encryption": "${DISTRO_ACCESS_KEY_ENCRYPTION}"
}
EOF
